### ISSUE TITLE
main.py name of the credentials file is wrong

### ISSUE THREAD

**Issue by s-wuest** [navs-svan/Beatport-DJCharts-Scraper#2]
https://github.com/navs-svan/Beatport-Spotify/blob/main/main.py
Line 332 -> credentials_path = os.path.join(os.path.dirname(__file__), "credentials.json")

should be credential.json (or rename the file)

**Comment by s-wuest** [comment]
Thanks for this wonderful tool
had to install scrapy and now it's working. looking forward to the results

**Comment by navs-svan** [comment]
Please do `mv credential.json credentials.json` to rename the file (I didn't want to commit my credentials to github)

**Comment by s-wuest** [comment]
Ah, that's why.
Yes. Did so. Tool is working like a charm 🙌🏼
